CREATE SCHEMA IF NOT EXISTS concierge;

CREATE TABLE email
(
    id    bigint generated by default as identity primary key,
    email varchar(255) not null
);

CREATE TABLE "user"
(
    id            bigint generated by default as identity primary key,
    name          varchar(255)        not null,
    login         varchar(255) unique not null,
    password_hash varchar(255)        not null,
    registered_at timestamp           not null,
    visited_at    timestamp           not null,
    role          varchar(255) default 'TENANT',
    email_id      bigint
        constraint fk_email references "email"
);

CREATE TABLE street
(
    id   bigint generated by default as identity primary key,
    name varchar(255) not null
);

CREATE TABLE house_number
(
    id                  bigint generated by default as identity primary key,
    number              varchar(255)             not null,
    common_floor_number smallint                 not null,
    street_id           bigint
        constraint fk_street references "street" not null
);

CREATE TABLE floor
(
    id              bigint generated by default as identity primary key,
    number          smallint                                 not null,
    house_number_id bigint
        constraint fk_house_number references "house_number" not null
);

CREATE TABLE apartment
(
    id          bigint generated by default as identity primary key,
    number      smallint                       not null,
    room_number smallint,
    owner       varchar(255),
    email_id    bigint
        constraint fk_email references "email",
    floor_id    bigint
        constraint fk_floor references "floor" not null
);

CREATE TABLE heating
(
    id           bigint generated by default as identity primary key,
    measure      numeric                               not null,
    measure_dt   timestamp                             not null,
    apartment_id bigint
        constraint fk_apartment references "apartment" not null,
    user_id      bigint
        constraint fk_user references "user"           not null
);