version: "3.8"

services:
  postgres-concierge:
    container_name: postgres-concierge
    image: postgres:15.2
    restart: on-failure
    env_file:
      - .env
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./.docker-volumes/postgres:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pre_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      concierge-net:
        ipv4_address: 172.28.1.1

networks:
  concierge-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16