CREATE SCHEMA IF NOT EXISTS concierge;

create table email
(
    id      bigint generated by default as identity
        primary key,
    email   varchar(255) not null,
    address varchar(255) not null,
    user_id integer      not null
);

create table "user"
(
    id            bigint generated by default as identity
        primary key,
    name          varchar(255) not null,
    login         varchar(255) not null
        unique,
    password_hash varchar(255) not null,
    registered_at timestamp    not null,
    visited_at    timestamp    not null,
    role          varchar(255) default 'TENANT'::character varying
);

create table street
(
    id               integer generated by default as identity
        primary key,
    city             varchar(255) not null,
    created_at       timestamp,
    last_modified_at timestamp,
    name             varchar(255) not null
);

create table dwelling
(
    id                  integer generated by default as identity
        primary key,
    created_at          timestamp,
    floor_number        integer     not null,
    last_modified_at    timestamp,
    number              varchar(15) not null,
    start_measuring_day integer     not null,
    stop_measuring_day  integer     not null,
    street_id           integer     not null
        constraint fk_street_id
            references street
);

create table floor
(
    id               integer generated by default as identity
        primary key,
    apartment_number integer not null,
    created_at       timestamp,
    last_modified_at timestamp,
    number           integer not null,
    dwelling_id      integer not null
        constraint fk_dwelling_id
            references dwelling
);

create table apartment
(
    id               integer generated by default as identity
        primary key,
    created_at       timestamp,
    last_modified_at timestamp,
    number           integer not null,
    owner            varchar(255),
    phone            varchar(15),
    type             varchar(255),
    floor_id         integer not null
        constraint fk_floor_id
            references floor
);

create table year
(
    id integer not null
        primary key
);

create table month
(
    id   integer     not null
        primary key,
    name varchar(15) not null
);

create table heating
(
    id               integer generated by default as identity
        primary key,
    created_at       timestamp,
    last_modified_at timestamp,
    measure          double precision not null,
    apartment_id     integer          not null
        constraint fk_apartment_id
            references apartment,
    month_id         integer          not null
        constraint fk_month_id
            references month,
    year_id          integer          not null
        constraint fk_year_id
            references year
);