CREATE SCHEMA IF NOT EXISTS concierge;

create table "user"
(
    id            integer generated by default as identity
        primary key,
    name          varchar(255) not null,
    login         varchar(255) not null
        unique,
    password_hash varchar(255) not null,
    registered_at timestamp    default now(),
    visited_at    timestamp    not null,
    role          varchar(255) default 'TENANT':: character varying
);

create table email
(
    id        integer generated by default as identity
        primary key,
    address   varchar(255) not null
        unique,
    is_active bool         not null,
    user_id   integer      not null
);

create table street
(
    id               integer generated by default as identity
        primary key,
    name             varchar(255) not null,
    city             varchar(255) not null,
    created_at       timestamp default now(),
    last_modified_at timestamp    not null
);

create table dwelling
(
    id                  integer generated by default as identity
        primary key,
    number              varchar(15) not null,
    start_measuring_day integer     not null,
    stop_measuring_day  integer     not null,
    created_at          timestamp default now(),
    last_modified_at    timestamp,
    street_id           integer     not null
        constraint fk_street_id
            references street
);

create table section
(
    id           integer generated by default as identity
        primary key,
    number       integer not null,
    created_at   timestamp default now(),
    dwelling_id  integer not null
        constraint fk_dwelling_id
            references dwelling
);

create table floor
(
    id               integer generated by default as identity
        primary key,
    number           integer   not null,
    created_at       timestamp not null,
    section_id       integer   not null
        constraint fk_section_id
            references section
);

create table apartment
(
    id               integer generated by default as identity
        primary key,
    number           integer   not null,
    type             varchar(255),
    owner            varchar(255),
    phone            varchar(15),
    created_at       timestamp default now(),
    last_modified_at timestamp not null,
    dwelling_id      integer   not null
        constraint fk_dwelling_id
            references dwelling,
    floor_id         integer   not null
        constraint fk_floor_id
            references floor
);

create table year
(
    id integer not null
        primary key
);

INSERT INTO year (id)
VALUES (2022);
INSERT INTO year (id)
VALUES (2023);
INSERT INTO year (id)
VALUES (2024);

create table month
(
    id         integer     not null
        primary key,
    name       varchar(15) not null,
    short_name varchar(3)  not null
);

INSERT INTO month (id, name, short_name)
VALUES (1, 'Январь', 'Jan');
INSERT INTO month (id, name, short_name)
VALUES (2, 'Февраль', 'Feb');
INSERT INTO month (id, name, short_name)
VALUES (3, 'Март', 'Mar');
INSERT INTO month (id, name, short_name)
VALUES (4, 'Апрель', 'Apr');
INSERT INTO month (id, name, short_name)
VALUES (5, 'Май', 'May');
INSERT INTO month (id, name, short_name)
VALUES (6, 'Июнь', 'Jun');
INSERT INTO month (id, name, short_name)
VALUES (7, 'Июль', 'Jul');
INSERT INTO month (id, name, short_name)
VALUES (8, 'Август', 'Aug');
INSERT INTO month (id, name, short_name)
VALUES (9, 'Сентябрь', 'Sep');
INSERT INTO month (id, name, short_name)
VALUES (10, 'Октябрь', 'Oct');
INSERT INTO month (id, name, short_name)
VALUES (11, 'Ноябрь', 'Nov');
INSERT INTO month (id, name, short_name)
VALUES (12, 'Декабрь', 'Dec');

create table heating
(
    id               integer generated by default as identity
        primary key,
    measure          double precision not null,
    created_at       timestamp default now(),
    last_modified_at timestamp        not null,
    dwelling_id      integer          not null
        constraint fk_dwelling_id
            references dwelling,
    apartment_id     integer          not null
        constraint fk_apartment_id
            references apartment,
    month_id         integer          not null
        constraint fk_month_id
            references month,
    year_id          integer          not null
        constraint fk_year_id
            references year
);

create table file
(
    id         uuid      default gen_random_uuid() primary key,
    size       bigint       not null,
    bucket     varchar(255) not null,
    created_at timestamp default now()
);